/**
 * Tool: upscale_google_flow_image
 * Upscale an existing Google Flow image to 2K or 4K.
 */

import { z } from 'zod';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import { getCredential } from '../lib/db.js';
import { createProgress } from '../lib/progress.js';
import {
    upscaleImage,
    getAccountInstanceId, fetchRecaptchaToken, clearRecaptchaToken, reloadRecaptchaPage,
} from '../lib/google-flow-api.js';
import { lookupMediaId } from '../lib/media-cache.js';

export const name = 'upscale_google_flow_image';
export const description = `Upscale an existing Google Flow image to 2K or 4K. Requires the media_id from generate_google_flow_image.

⚠️ CRITICAL — SEQUENTIAL ONLY: All Google Flow tools share a SINGLE browser session. You MUST call them ONE AT A TIME, waiting for each call to fully complete before making the next. If you call multiple Google Flow tools in parallel, ALL calls WILL FAIL with timeouts and NO images/videos will be created.

RETRY GUIDANCE — when this tool fails:
- "PUBLIC_ERROR_HIGH_TRAFFIC" → cluster is overloaded. RETRY WITH THE SAME media_id after a short wait (5-15s). This is transient capacity, not anything wrong with the input.
- "PUBLIC_ERROR_UNUSUAL_ACTIVITY" / reCAPTCHA 403 → trust-score blip. Retry once.
- Any other error → retry once; if it still fails, report the exact error to the user instead of guessing.`;

export const schema = {
    media_id: z.string().optional().describe('The media ID of the image to upscale (from generate_google_flow_image)'),
    file_path: z.string().optional().describe('Absolute path to a Google Flow generated image. The tool will look up the cached media_id automatically. Alternative to media_id.'),
    resolution: z.enum(['2k', '4k']).default('2k').describe('Target resolution: 2k or 4k'),
    output_dir: z.string().optional().describe('Directory to save the upscaled image'),
};

export async function handler(params, extra) {
    const progress = createProgress(extra);
    await progress('Loading credentials...');

    const cred = getCredential();
    const token = cred.token;
    const projectId = cred.metadata.projectId;
    if (!projectId) throw new Error('GOOGLE_FLOW_PROJECT_ID is not set in .env file.');

    const sessionCookies = cred.metadata.sessionCookies || '';
    const instanceId = getAccountInstanceId(cred);

    // Resolve media_id: explicit param > cache lookup from file_path
    let mediaId = params.media_id || null;
    if (!mediaId && params.file_path) {
        mediaId = await lookupMediaId(params.file_path);
        if (mediaId) {
            await progress(`Found cached media ID for ${params.file_path}`);
        }
    }
    if (!mediaId) {
        return { content: [{ type: 'text', text: '❌ No media_id provided and no cached media_id found for the given file_path. Only images generated by Google Flow can be upscaled.' }] };
    }

    // Sticky-failure recovery: see upscale-video.js for the full rationale.
    // If the reCAPTCHA SDK on the page lifetime is poisoned, page.reload() recovers
    // it — fetching a fresh token from the same stale page does not.
    const MAX_OUTER_RETRIES = 1;
    let result = null;
    let lastError = null;
    for (let outerAttempt = 0; outerAttempt <= MAX_OUTER_RETRIES; outerAttempt++) {
        if (outerAttempt > 0) {
            await progress(`Reloading Chrome page and retrying upscale (attempt ${outerAttempt + 1})...`);
            await reloadRecaptchaPage(instanceId);
            await new Promise(r => setTimeout(r, 5000));
        }

        await progress('Getting reCAPTCHA token...');
        const recaptchaToken = await fetchRecaptchaToken(sessionCookies, 'IMAGE_GENERATION', instanceId);

        await progress(`Upscaling to ${params.resolution.toUpperCase()}...`);
        try {
            result = await upscaleImage(token, projectId, mediaId, params.resolution, recaptchaToken, instanceId, sessionCookies);
            await clearRecaptchaToken(recaptchaToken);
            if (result.encodedImage) break;
            lastError = new Error('Upscale returned no image data');
        } catch (e) {
            await clearRecaptchaToken(recaptchaToken);
            lastError = e;
            const isStickyFailure = /UNUSUAL_ACTIVITY|HIGH_TRAFFIC|reCAPTCHA|403/i.test(e.message);
            if (outerAttempt >= MAX_OUTER_RETRIES || !isStickyFailure) throw e;
            console.error(`[FlowImage] Upscale failed (${e.message}) — will reload page and retry once`);
        }
    }

    // Chrome stays alive for reuse (idle timer auto-closes after 10 min)

    if (!result || !result.encodedImage) {
        return { content: [{ type: 'text', text: `⚠️ Upscale returned no image data: ${lastError?.message || 'unknown error'}` }] };
    }

    await progress('Saving upscaled image...');
    const uploadDir = process.env.UPLOAD_DIR || './uploads';
    const outputDir = params.output_dir || join(uploadDir, 'mcp-generated');
    await mkdir(outputDir, { recursive: true });

    const filename = `gflow_${params.resolution}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.jpg`;
    const filepath = join(outputDir, filename);
    await writeFile(filepath, Buffer.from(result.encodedImage, 'base64'));

    return {
        content: [{ type: 'text', text: `✅ Image upscaled to ${params.resolution.toUpperCase()}!\n\n**File**: ${filepath}\n**Media ID**: ${mediaId}` }],
    };
}
