/**
 * Tool: upscale_google_flow_video
 * Upscale an existing Google Flow video to 1080p.
 */

import { z } from 'zod';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import { v4 as uuidv4 } from 'uuid';
import fetch from 'node-fetch';
import { getCredential } from '../lib/db.js';
import { createProgress } from '../lib/progress.js';
import {
    submitVideoUpscale, pollUpscaleCompletion, fetchVideoDownloadUrl,
    VIDEO_ASPECT_RATIO_MAP,
    getAccountInstanceId, fetchRecaptchaToken,
} from '../lib/google-flow-api.js';
import { lookupMediaId } from '../lib/media-cache.js';

export const name = 'upscale_google_flow_video';
export const description = `Upscale an existing Google Flow video from 720p to 1080p. Requires the media_id from generate_google_flow_video.

⚠️ CRITICAL — SEQUENTIAL ONLY: All Google Flow tools share a SINGLE browser session. You MUST call them ONE AT A TIME, waiting for each call to fully complete before making the next. If you call multiple Google Flow tools in parallel, ALL calls WILL FAIL with timeouts and NO images/videos will be created.

RETRY GUIDANCE — when this tool fails:
- "PUBLIC_ERROR_HIGH_TRAFFIC" → Veo cluster is overloaded. RETRY WITH THE SAME media_id after a short wait (5-15s). This is transient capacity, not anything wrong with the input.
- "PUBLIC_ERROR_UNUSUAL_ACTIVITY" / reCAPTCHA 403 → trust-score blip. Retry once.
- Any other error → retry once; if it still fails, report the exact error to the user instead of guessing.`;

export const schema = {
    media_id: z.string().optional().describe('The media ID of the video to upscale (from generate_google_flow_video)'),
    file_path: z.string().optional().describe('Absolute path to a Google Flow generated video. The tool will look up the cached media_id automatically. Alternative to media_id.'),
    aspect_ratio: z.enum(['9:16', '16:9', '1:1']).default('9:16').describe('Must match the original video aspect ratio'),
    output_dir: z.string().optional().describe('Directory to save the upscaled video'),
};

export async function handler(params, extra) {
    const progress = createProgress(extra);
    await progress('Loading credentials...');

    const cred = getCredential();
    const token = cred.token;
    const projectId = cred.metadata.projectId;
    if (!projectId) throw new Error('GOOGLE_FLOW_PROJECT_ID is not set in .env file.');

    const sessionCookies = cred.metadata.sessionCookies || '';
    const instanceId = getAccountInstanceId(cred);
    const aspectRatio = VIDEO_ASPECT_RATIO_MAP[params.aspect_ratio] || 'VIDEO_ASPECT_RATIO_PORTRAIT';

    // Resolve media_id: explicit param > cache lookup from file_path
    let mediaId = params.media_id || null;
    if (!mediaId && params.file_path) {
        mediaId = await lookupMediaId(params.file_path);
        if (mediaId) {
            await progress(`Found cached media ID for ${params.file_path}`);
        }
    }
    if (!mediaId) {
        return { content: [{ type: 'text', text: '❌ No media_id provided and no cached media_id found for the given file_path. Only videos generated by Google Flow can be upscaled.' }] };
    }

    await progress('Getting reCAPTCHA token...');
    const recaptchaToken = await fetchRecaptchaToken(sessionCookies, 'VIDEO_GENERATION', instanceId);

    await progress('Submitting 1080p upscale...');
    const upResult = await submitVideoUpscale(token, projectId, mediaId, aspectRatio, recaptchaToken, instanceId);

    if (!upResult.upsampledMediaId) {
        // Do NOT close Chrome here — keep the warm browser alive so the next call
        // reuses the same logged-in profile (preserves reCAPTCHA trust score).
        // The 10-min idle timer is the only sanctioned mid-life close path.
        return { content: [{ type: 'text', text: '⚠️ Video upscale failed.' }] };
    }

    await progress('Polling upscale progress...');
    await pollUpscaleCompletion(token, projectId, upResult.upsampledMediaId);

    await progress('Getting download URL...');
    const videoUrl = await fetchVideoDownloadUrl(token, projectId, upResult.upsampledMediaId, sessionCookies, instanceId);

    const uploadDir = process.env.UPLOAD_DIR || './uploads';
    const outputDir = params.output_dir || join(uploadDir, 'mcp-generated');
    await mkdir(outputDir, { recursive: true });

    let videoPath = '';
    if (videoUrl) {
        try {
            await progress('Downloading upscaled video...');
            const videoRes = await fetch(videoUrl);
            if (videoRes.ok) {
                const videoBuffer = Buffer.from(await videoRes.arrayBuffer());
                videoPath = join(outputDir, `video_1080p_${uuidv4().substring(0, 8)}.mp4`);
                await writeFile(videoPath, videoBuffer);
            }
        } catch (e) {
            console.error(`[MCP] Video download failed: ${e.message}`);
        }
    }

    // Chrome stays alive for reuse (idle timer auto-closes after 10 min)

    return {
        content: [{ type: 'text', text: `✅ Video upscaled to 1080p!\n\n**File**: ${videoPath || 'N/A'}\n**Download URL**: ${videoUrl || 'N/A'}` }],
    };
}
