import LegalLayout from './LegalLayout.jsx';

export default function PrivacyPolicy() {
    return (
        <LegalLayout title="Privacy Policy" lastUpdated="May 17, 2026">
            <p>
                This Privacy Policy explains how THHFlow ("we", "our", or "the Service"), operated at
                <a href="https://thhflow.com"> thhflow.com</a>, collects, uses, stores, and protects information when
                you use our AI workflow automation platform. By creating an account or using the Service, you agree
                to the practices described below.
            </p>

            <h2>1. Information We Collect</h2>

            <h3>1.1. Account information</h3>
            <ul>
                <li><strong>Email address</strong> and an optional <strong>display name</strong> you provide when registering.</li>
                <li>A <strong>hashed password</strong> (bcrypt) — we never store passwords in plain text.</li>
                <li>If you sign in with Google, we receive your <strong>Google account email, name, and profile picture URL</strong> through Google Identity Services. We do not receive your Google password.</li>
            </ul>

            <h3>1.2. Content you create</h3>
            <ul>
                <li>Workflows, nodes, prompts, and configuration you build on the canvas.</li>
                <li>Files you upload (text, images, audio, video) and files generated by AI services on your behalf.</li>
                <li>Execution logs, error messages, and intermediate outputs produced by workflow runs.</li>
            </ul>

            <h3>1.3. Third-party credentials you choose to store</h3>
            <p>
                To run AI nodes you may save credentials for third-party providers such as Google Flow, Gemini,
                ChatGPT/OpenAI, OpenRouter, or Telegram. These credentials are stored in our database and used solely
                to call those services on your behalf. You can delete them at any time from the Credentials page.
            </p>

            <h3>1.4. Technical data</h3>
            <ul>
                <li>IP address, browser type, and timestamps of API requests (kept in server logs).</li>
                <li>A JSON Web Token (JWT) stored in your browser's localStorage to keep you signed in.</li>
                <li>Browser cookies set by Google Identity Services and reCAPTCHA where applicable.</li>
            </ul>

            <h2>2. How We Use Your Information</h2>
            <ul>
                <li>To create and authenticate your account.</li>
                <li>To execute the workflows you build and deliver the outputs to you in real time over Socket.IO.</li>
                <li>To send transactional emails such as email verification and security notices.</li>
                <li>To monitor, debug, and improve the reliability of the Service.</li>
                <li>To detect and prevent abuse, fraud, and violations of our Terms of Service.</li>
            </ul>
            <p>
                We do <strong>not</strong> sell your personal information. We do not use the content of your workflows
                or uploaded files to train any machine-learning model.
            </p>

            <h2>3. Third-Party AI Providers</h2>
            <p>
                When you run a node that calls a third-party AI service, the inputs you provide (prompts, files,
                parameters) are sent directly to that provider's API using the credentials you supplied. Each provider
                has its own privacy policy, which governs how they handle that data:
            </p>
            <ul>
                <li><strong>Google</strong> (Gemini, Google Flow / Veo) — <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">policies.google.com/privacy</a></li>
                <li><strong>OpenAI</strong> (ChatGPT) — <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noreferrer">openai.com/policies/privacy-policy</a></li>
                <li><strong>OpenRouter</strong> — <a href="https://openrouter.ai/privacy" target="_blank" rel="noreferrer">openrouter.ai/privacy</a></li>
                <li><strong>Telegram</strong> (if you connect a bot) — <a href="https://telegram.org/privacy" target="_blank" rel="noreferrer">telegram.org/privacy</a></li>
            </ul>
            <p>
                You are responsible for reviewing those policies before submitting data to a provider through THHFlow.
            </p>

            <h2>4. Cookies and Local Storage</h2>
            <p>We use only the storage strictly necessary to operate the Service:</p>
            <ul>
                <li><strong>localStorage</strong> — your JWT session token and your theme preference (light/dark).</li>
                <li><strong>Cookies set by Google Identity Services</strong> — required for "Sign in with Google" to work.</li>
                <li><strong>Cookies set by Google reCAPTCHA</strong> — required to protect against automated abuse on AI provider calls.</li>
            </ul>
            <p>We do not use advertising cookies or third-party analytics trackers.</p>

            <h2>5. Data Storage and Security</h2>
            <ul>
                <li>Application data is stored on a Google Cloud Platform virtual machine located in the <strong>asia-southeast1</strong> region.</li>
                <li>Passwords are hashed with bcrypt before being persisted.</li>
                <li>All traffic between your browser and the Service is encrypted in transit via HTTPS (TLS).</li>
                <li>Database backups are retained for operational recovery and are deleted on a rolling basis.</li>
            </ul>
            <p>
                No method of transmission or storage on the Internet is 100% secure. We take reasonable measures to
                protect your data but cannot guarantee absolute security.
            </p>

            <h2>6. Data Retention</h2>
            <ul>
                <li>Account data is retained for as long as your account is active.</li>
                <li>Workflow definitions and execution artifacts are retained until you delete them or your account.</li>
                <li>Uploaded files older than 90 days may be removed automatically to manage storage.</li>
                <li>Server access logs are retained for up to 30 days for security and debugging purposes.</li>
            </ul>

            <h2>7. Your Rights</h2>
            <p>You have the right to:</p>
            <ul>
                <li><strong>Access</strong> the personal information we hold about you.</li>
                <li><strong>Correct</strong> inaccurate information through your profile or by contacting us.</li>
                <li><strong>Delete</strong> your account and all associated data. You can request deletion by emailing us.</li>
                <li><strong>Export</strong> your workflows in JSON format from the dashboard.</li>
                <li><strong>Withdraw consent</strong> for optional processing at any time.</li>
            </ul>
            <p>
                Where applicable under the EU General Data Protection Regulation (GDPR), the UK Data Protection Act,
                or Vietnam's Personal Data Protection Decree (Nghị định 13/2023/NĐ-CP), you may also lodge a complaint
                with your local data protection authority.
            </p>

            <h2>8. Children's Privacy</h2>
            <p>
                THHFlow is not intended for users under the age of 13 (or 16 in jurisdictions where that is the
                minimum age of consent for online services). We do not knowingly collect personal information from
                children. If you believe a child has provided us with information, please contact us so we can delete it.
            </p>

            <h2>9. International Transfers</h2>
            <p>
                Your data may be processed in countries other than your own when you call third-party AI providers.
                We do not transfer your data to any other party except as required to deliver the Service.
            </p>

            <h2>10. Changes to This Policy</h2>
            <p>
                We may update this Privacy Policy from time to time. We will post the new version on this page and
                update the "Last updated" date above. Material changes will be notified via email to the address
                associated with your account.
            </p>

            <h2>11. Contact</h2>
            <p>
                For questions about this Privacy Policy or to exercise any of your rights, contact:
                <br />
                <strong>Email:</strong> <a href="mailto:hoanghuycptqt@gmail.com">hoanghuycptqt@gmail.com</a>
                <br />
                <strong>Website:</strong> <a href="https://thhflow.com">thhflow.com</a>
            </p>
        </LegalLayout>
    );
}
